### ISSUE TITLE
Make an interactive demo for the statement of the optimization objective

### ISSUE THREAD

**Issue by j2kun** [j2kun/svm-sequential-minimal-optimization#2]
The demo should have

 - [ ] A hyperplane passing through the origin, whose normal vector you can drag to reorient the hyperplane
 - [x] An example set of points
 - [ ] Show which positive and negative example is the closest to the hyperplane
 - [ ] Draw parallel lines for w*x = 1 to see the normalization
 - [ ] Show the value of the (algebraic) margin as a number.

Maybe also a color map showing the margin as a function of the (x,y) coordinates of the normal vector?

**Comment by j2kun** [comment]
Gonna use this as a guide b/c I can't remember js

https://simonsarris.com/making-html5-canvas-useful/

**Comment by irpap** [comment]
I'm not very good at js, but I had to use d3 recently to draw a graph and that was ok. But I haven't really used canvas much so I can't compare. 
http://maurizzzio.github.io/function-plot/ this might be interesting?

**Comment by j2kun** [comment]
@irpap I think I'll do this one, and since realizing I want to let people drag/drop stuff around I think canvas is too much work for what it's worth. So I'll tinker with this one in my free time. You should totally focus on the math, and keep asking questions :)

**Comment by j2kun** [comment]
OK you know d3, so I'll suck it up and use d3. 

Gonna add dragging for the arrowhead to this PR, then merge. https://github.com/j2kun/svm-sequential-minimal-optimization/pull/3

Rest of the checklist can be a subsequent PR
