### ISSUE TITLE
Math rendering

### ISSUE THREAD

**Issue by j2kun** [j2kun/svm-sequential-minimal-optimization#4]
Find a way to render Markdown + Mathjax in github documents.

**Comment by irpap** [comment]
I had success with this chrome extension: [GitHub with MathJax](https://chrome.google.com/webstore/detail/github-with-mathjax/ioemnmodlmafdkllaclgeombjnmnbima). I tried it using a markdown file with some MathJax like   If $A \overset{\mbox{f}}{\longrightarrow} B \overset{\mbox{g}}{\longrightarrow} C \overset{\mbox{h}}{\longrightarrow} D$, then $(h  \circ  g)  \circ  f = h  \circ  (g  \circ  f)$

**Comment by j2kun** [comment]
Fantastic!
